


export const ACCESS_LIMITS = Object.freeze({
    NONE: 'NONE',
    SALES_BILL: 'SALES_BILL',
    SALES_PAYMENT: 'SALES_PAYMENT',
    SALES_PAYMENT_VIEW: 'SALES_PAYMENT_VIEW',
    PURCHASE_BILL: 'PURCHASE_BILL',
    PURCHASE_PAYMENT: 'PURCHASE_PAYMENT',
    PURCHASE_PAYMENT_VIEW: 'PURCHASE_PAYMENT_VIEW',
    FUND: 'FUND',
    MATERIAL_MANAGE: 'MATERIAL_MANAGE',
});
